#!/usr/bin/env python3
"""Build a deterministic release ZIP and record its exact payload in a new manifest."""
import argparse
import json
import zipfile
from pathlib import Path
from verify import ROOT,sha,safe

def main():
    p=argparse.ArgumentParser();p.add_argument('manifest',type=Path)
    p.add_argument('payload',type=Path);p.add_argument('output',type=Path);a=p.parse_args()
    m=json.loads(a.manifest.read_text())
    if a.output.exists():raise ValueError('refusing to overwrite a versioned archive')
    files={}
    for f in sorted(a.payload.rglob('*')):
        if f.is_symlink():raise ValueError('payload must not contain symlinks')
        if not f.is_file():continue
        name=safe(f.relative_to(a.payload).as_posix())
        if name=='FILES.json':raise ValueError('FILES.json is generated by the packager')
        files[name]={'bytes':f.stat().st_size,'sha256':sha(f)}
    if not {'LICENSE','CREDITS.md','NOTICE.md'}<=files.keys():raise ValueError('missing license/credits/notices')
    index={'assetId':m['id'],'version':m['version'],'files':files}
    a.output.parent.mkdir(parents=True,exist_ok=True)
    with zipfile.ZipFile(a.output,'w',compression=zipfile.ZIP_DEFLATED,compresslevel=6) as z:
        for name in list(files)+['FILES.json']:
            info=zipfile.ZipInfo(name,date_time=(1980,1,1,0,0,0));info.compress_type=zipfile.ZIP_DEFLATED
            info.external_attr=0o100644<<16
            data=(json.dumps(index,indent=2)+'\n').encode() if name=='FILES.json' else (a.payload/name).read_bytes()
            z.writestr(info,data)
    m['files']=files
    m['release']['archive']={'name':a.output.name,'bytes':a.output.stat().st_size,'sha256':sha(a.output),
        'url':f"https://github.com/lincolnaleixo/retro-cartridge-models/releases/download/{m['release']['tag']}/{a.output.name}"}
    a.manifest.write_text(json.dumps(m,indent=2)+'\n')
    print(f'Packaged {len(files)} files: {a.output} ({a.output.stat().st_size} bytes)')

if __name__=='__main__':main()
